name: jp2-playground
services:
  python:
    config: {}
    type: python:3
    command: tail -f /dev/null
    build_as_root:
      - grep '^deb ' /etc/apt/sources.list | perl -pe 's/deb /deb-src /' >> /etc/apt/sources.list
      - apt-get update -qq && apt-get install -y python3-lxml pylint libxml2-dev libxslt1-dev python3-dev zlib1g-dev lib32z1-dev libffi-dev libssl-dev libjpeg-dev imagemagick libopenjp2-7-dev libtiff-dev && apt-get build-dep -y lxml
    build:
      - cd /app && pip install --upgrade pip && pip install Cython && pip install -r requirements.txt
    scanner: false

tooling:
  python:
    service: python
    cmd: python
  pip:
    service: python
    cmd: pip
